### PR TITLE
Fix "unique && nameOnly" error

### PR DESCRIPTION
**Pull request by saiki-k**

### CODE REVIEW

**Comment by fatman-** [comment]
I'm unsure of the cause behind the final failing check in TravisCI.

**Comment by fatman-** [comment]
Fixes #4

**Comment by radiovisual** [comment]
I think the error is an unrelated issue coming from AVA, but I can be certain until I take a closer look

**Comment by radiovisual** [comment]
I confirmed that the error is related to AVA running in Travis CI on Version 6. I moved the test runner to tape and it all passes without a problem.

**Pull request merged**
